### ISSUE TITLE
Node drop execution with sigfault

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#1421]
### Problem

When we tries to upload specific contracts to node on M1 macos, then we receive node execution drop with message
```
illegal hardware instruction
```

### Steps

1. env
```
main sc_cli::runner: ⛓  Native runtime: gear-node-1680 (gear-node-1.tx1.au1)
main sc_sysinfo: 💻 Operating system: macos
main sc_sysinfo: 💻 CPU architecture: aarch64
```
2. run node
```
./target/release/gear-node --dev  --execution=wasm
```
3. upload smart contract [lol.wasm.zip](https://github.com/gear-tech/gear/files/9485482/lol.wasm.zip)
4. receive an error during `on_idle`
```
illegal hardware instruction
```

### Possible Solution

May be there is some bugs  in `wasmer` for M1 chip - `wasmer` compile WASM code into machine code with some number of  illegal instructions.

**Comment by grishasobol** [comment]
Currently found one more test [linux_panic.zip](https://github.com/gear-tech/gear/files/9507314/linux_panic.zip) which cause both panic on macos:
```
illegal hardware instruction
```
and panic on linux:
```
[1]    3528395 segmentation fault  ./target/release/gear-node --dev -l0 --execution=wasm 2>&1
```

So, mark this problem as asap

**Comment by grishasobol** [comment]
Reduced test which reproduce the problem:
```
(module
  (type (;0;) (func))
  (import "env" "memory" (memory (;0;) 0))
  (func (;0;) (type 0)
    call 0
  )
  (export "init" (func 0))
)
```

**Comment by grishasobol** [comment]
Version that problem is in wasmer generated code is not right. But problem is in wasm signal handler. Cannot find the reason and reproduce this on standalone test for `wasmer`.

```#0  0x0000564b3230c5e4 in core::mem::replace ()
#1  0x0000564b3231195c in core::cell::Cell<T>::replace ()
#2  0x0000564b32311884 in core::cell::Cell<T>::set ()
#3  0x0000564b31dd8987 in wasmer_vm::trap::traphandlers::on_host_stack::{{closure}}::{{closure}} ()
#4  0x0000564b31d66003 in std::thread::local::LocalKey<T>::try_with ()
#5  0x0000564b31d65894 in std::thread::local::LocalKey<T>::with ()
#6  0x0000564b31dd88f3 in wasmer_vm::trap::traphandlers::on_host_stack::{{closure}} ()
#7  0x0000564b31dd7e4e in <scopeguard::ScopeGuard<T,F,S> as core::ops::drop::Drop>::drop ()
#8  0x0000564b31d8975b in core::ptr::drop_in_place<scopeguard::ScopeGuard<(),wasmer_vm::trap::traphandlers::on_host_stack<<wasmer_vm::vmcontext::VMDynamicFunctionContext<wasmer::sys::externals::function::DynamicFunction<wasmer::sys::externals::function::inner::WithoutEnv>> as wasmer::sys::externals::function::VMDynamicFunctionCall<wasmer::sys::externals::function::DynamicFunction<wasmer::sys::externals::function::inner::WithoutEnv>>>::func_wrapper::{{closure}},core::result::Result<core::result::Result<(),wasmer_engine::trap::error::RuntimeError>,alloc::boxed::Box<dyn core::any::Any+core::marker::Send>>>::{{closure}}>> ()
#9  0x0000564b31dd889a in wasmer_vm::trap::traphandlers::on_host_stack ()
#10 0x0000564b31dd54b7 in <wasmer_vm::vmcontext::VMDynamicFunctionContext<T> as wasmer::sys::externals::function::VMDynamicFunctionCall<T>>::func_wrapper ()
#11 0x00007f9006c12109 in ?? ()
#12 0x0000000000001900 in ?? ()
#13 0x0000000000000000 in ?? ()```

**Comment by gshep** [comment]
> Reduced test which reproduce the problem:
> 
> ```
> (module
>   (type (;0;) (func))
>   (import "env" "memory" (memory (;0;) 0))
>   (func (;0;) (type 0)
>     call 0
>   )
>   (export "init" (func 0))
> )
> ```

This looks like a commonplace recursion, doesn't it?
