### ISSUE TITLE
`wasm-builder` cause failures in vs-code rust analyser extensions 

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#3925]
### Problem

I always receive this error while using rust-analyser extension.
```
error: failed to run custom build command for `demo-meta-state-v3 v0.1.0 (./examples/new-meta/state-v3)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `./target/debug/build/demo-meta-state-v3-83b35be5debdcd63/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at utils/wasm-builder/src/cargo_command.rs:49:53:
  Failed to get toolchain from rustup: cargo toolchain is invalid `/.rustup/toolchains/nightly-2024-01-25-aarch64-apple-darwin`

  Stack backtrace:
     0: std::backtrace_rs::backtrace::libunwind::trace
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
     1: std::backtrace_rs::backtrace::trace_unsynchronized
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2: std::backtrace::Backtrace::create
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/backtrace.rs:331:13
     3: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
     4: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
     5: gear_wasm_builder::cargo_toolchain::Toolchain::try_from_rustup
     6: gear_wasm_builder::cargo_command::CargoCommand::new
     7: gear_wasm_builder::WasmBuilder::create
     8: gear_wasm_builder::WasmBuilder::new_metawasm
     9: gear_wasm_builder::build_metawasm
    10: build_script_build::main
    11: core::ops::function::FnOnce::call_once
    12: std::sys_common::backtrace::__rust_begin_short_backtrace
    13: std::rt::lang_start::{{closure}}
    14: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/core/src/ops/function.rs:284:13
    15: std::panicking::try::do_call
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/panicking.rs:554:40
    16: std::panicking::try
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/panicking.rs:518:19
    17: std::panic::catch_unwind
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/panic.rs:142:14
    18: std::rt::lang_start_internal::{{closure}}
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/rt.rs:148:48
    19: std::panicking::try::do_call
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/panicking.rs:554:40
    20: std::panicking::try
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/panicking.rs:518:19
    21: std::panic::catch_unwind
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/panic.rs:142:14
    22: std::rt::lang_start_internal
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/rt.rs:148:20
    23: std::rt::lang_start
    24: _main
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/panicking.rs:647:5
     1: core::panicking::panic_fmt
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/core/src/panicking.rs:72:14
     2: core::result::unwrap_failed
               at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/core/src/result.rs:1649:5
     3: core::result::Result<T,E>::expect
     4: gear_wasm_builder::cargo_command::CargoCommand::new
     5: gear_wasm_builder::WasmBuilder::create
     6: gear_wasm_builder::WasmBuilder::new_metawasm
     7: gear_wasm_builder::build_metawasm
     8: build_script_build::main
     9: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
As I can see this is our error:
https://github.com/gear-tech/gear/blob/0dbc1c2b79bb005f19a3ae74b27c9c03c806384c/utils/wasm-builder/src/builder_error.rs#L37-L38

**Comment by grishasobol** [comment]
was fixed
