### ISSUE TITLE
encode.js has wrong output when my meta.wasm file is input

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#432]
### Problem

when I try to encode file
[fungible_token.meta.zip](https://github.com/gear-tech/gear/files/7583397/fungible_token.meta.zip)
using script encode.js, I have output of many many strings:
...
1058696
1058696
1058696
1058696
1058696
1058696
1058696
1058696
1058696
1058696
1058696
1058696
1058696
1058696
1058696
1058696
...
It's wrong output that cannot be parsed by gtest.

### Steps

node gtest/src/js/encode.js -p fungible_token.meta.wasm -t init_input -j '{"name":"GearToken","symbol":"GRT"}'

fungible_token.meta.wasm - it's our wasm file

**Comment by grishasobol** [comment]
Forget to add, that for that output encode.js returns 0

**Comment by grishasobol** [comment]
I have one other example. May be the problem is in my wasm files, but this script output is completely uninformative
[fungible_token1.meta.zip](https://github.com/gear-tech/gear/files/7587182/fungible_token1.meta.zip)

The same reproduce: node gtest/src/js/encode.js -p fungible_token.meta.wasm -t init_input -j '{"name":"GearToken","symbol":"GRT"}'

But script now exit with error:
```
/home/gregory/src/gear/gtest/src/js/node_modules/@polkadot/util/assert.cjs:34
    throw new Error((0, _function.isFunction)(message) ? message() : message);
          ^

Error: Unable to register circular 0 === 0
    at assert (/home/gregory/src/gear/gtest/src/js/node_modules/@polkadot/util/assert.cjs:34:11)
    at TypeRegistry._registerObject (/home/gregory/src/gear/gtest/src/js/node_modules/@polkadot/types/create/registry.cjs:564:26)
    at TypeRegistry.register (/home/gregory/src/gear/gtest/src/js/node_modules/@polkadot/types/create/registry.cjs:549:12)
    at CreateType.registerTypes (/home/gregory/src/gear/gtest/src/js/node_modules/@gear-js/api/lib/CreateType.js:78:23)
    at CreateType.createRegistry (/home/gregory/src/gear/gtest/src/js/node_modules/@gear-js/api/lib/CreateType.js:55:14)
    at CreateType.encode (/home/gregory/src/gear/gtest/src/js/node_modules/@gear-js/api/lib/CreateType.js:93:92)
    at Function.encode (/home/gregory/src/gear/gtest/src/js/node_modules/@gear-js/api/lib/CreateType.js:117:27)
    at /home/gregory/src/gear/gtest/src/js/encode.js:28:30
```

**Comment by grishasobol** [comment]
@osipov-mit  and @breathx  give me an advice to remove "full" feature from parity-scale-codec:
```
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive","full"] }
```
But unfortunately I have an example where test is built without 'full' feature. 
[demo_async_multisig.meta.zip](https://github.com/gear-tech/gear/files/7597808/demo_async_multisig.meta.zip)

We have in gstd dependency:
```
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive","full"] }
```
If we remove 'full' this test **demo_async_multisig** can be built.
But if we try to use encode.js for it we have the same problem:
```
node gtest/src/js/encode.js -p target/wasm32-unknown-unknown/release/demo_async_multisig.meta.wasm -t init_input -j '{"name":"GearToken","symbol":"GRT"}
1067716
1067716
1067716
1067716
1067716
1067716
1067716
1067716
1067716
1067716
1067716
1067716
1067716
1067716
1067716
1067716
1067716
1067716
...
```
